### ISSUE TITLE
Create email verification for admission users + Applicant QoL stuff

### ISSUE THREAD

**Issue by Frenje123** [Samfundet/Samfundet#1018]
**Email verification will follow these rules:**

- Applicant registers, receives an email and needs to click on the link to proceed
- The link will immediately log the user into their account
- If the user tries to log in, without a verified user, they will be informed about the verification process and receive a new email. This will also count as a login attempt.

### Subtasks to finish in the process:

- [x] Add email confirmation on applicant registration form (#1025) 
- [x] Add possibility to login with phone number as applicant  (#1027 and #1028)
- [ ] Add lockout policy for admission users (#1029)
- [x] Create email verification, and count unverified logins as failed logins
- [x] Fix minor bugs to improve QoL for applicants (#1031 and #1032)
